### ISSUE TITLE
User needs statements

### ISSUE THREAD

**Issue by dominicpanarello** [UMEC/healthcare-workforce#3]

**Comment by Randy-Gregory-II** [comment]
Second draft:

Academic Administrators need a way to **proactively know the health care needs of the population** so that they can **adequately secure funding for programs** that are **best aligned to the needs of the community**.

Members of an education institution need to a way to know **what programs to create from a people and cost perspective** so that they can **output the right people to fulfill the right demands.**

The administration of a medical organization **need a way to understand the current & future health needs of a community**, so they can **appropriately train and staff their employees** to fulfill ever changing needs.

**Comment by Randy-Gregory-II** [comment]
Thought process: https://app.mural.co/invitation/mural/ibmhealthcorps2816/1539621966011?sender=rjgregor&key=d40ba38e-dbf7-4390-b710-61a0aae64f05

**Comment by Randy-Gregory-II** [comment]
Edits as per @dominicpanarello 

Academic Administrators need a way to proactively know the health care needs gaps of the population so that they can adequately secure funding for programs that are best aligned to the needs of the community.


Members of an education institution need to a way to know what candidate programs to create from a people and cost perspective so that they can output the right people to fulfill the right demands.

**Comment by Randy-Gregory-II** [comment]
Edits made on 10/21 based on feedback from Review Day 10/19

## Primary User Archetypes of the Solution
Academic Administrators need a way to proactively **understand the health care gaps of the population ** so that they can **secure funding for candidate programs ** that are best aligned to the needs of the community.

Members of an education institution need to a way to know ** what candidate programs to create** from a people and cost perspective so that they can **output the right graduates** to fulfill the needs of the community.

The **administration of a clinical organization** need a way to **understand the current & future health needs of their communities**, so they can **appropriately train and staff their employees**, to fulfill  ever changing needs.

**Legislators (and their committees)** need to be able to **understand the needs of the healthcare community** from an **unbiased source of information** so they can make the **most appropriate decisions when creating policies that affect the population**.

## Secondary User Archetypes of the solution

**Care Givers** need to know how to **maximize use of their resources** (including the creation of new roles) to best provide **high quality care at lower prices** (to the clinic) under consistently changing circumstances.

**Patients** need to **not worry about a lack of services in their community** or **not being able to receive the correct services**, so that they can be **treated efficiently and correctly**.

**Comment by Randy-Gregory-II** [comment]
Statements have been committed to the deck, as per @lexicas . Closing this
